### ISSUE TITLE
translation limited to just one language

### ISSUE THREAD

**Issue by GbotemiB** [ffreemt/google-itranslate#2]
Hi, I tried using your source code to translate from a different language to english. I couldnt use it to do the translation.

**Comment by ffreemt** [comment]
I just installed `itranslate` in a new env. It looks ok. 
```
python  -c "from itranslate import itranslate as itrans; print(itrans('test this and that', to_lang='de'))"
# Testen Sie das und das
```
Can you show me what you did? Note the option may be different from those used in other packages.

**Comment by GbotemiB** [comment]
Well, i didnt know the syntax to choose the target language.

Thanks
